language: java

sudo: false

jdk:
  - oraclejdk8

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "nn4GGXnlQpRlt4IcgeEgmMKSA4byJu42P2Tf3h7fSnbX4LmacecAXn8Z3gvkSu1RWKbmMAKW3y7I2NASy8npyy4MM2/3a56Wm8TXCH44kndt24V5pXcgsogU/lDDz2wRuoIo371ZUylf6yezf4Dbc1cphxKRazDulxJH3Kp1wKI="

addons:
  coverity_scan:
    # https://docs.travis-ci.com/user/coverity-scan/
    project:
      name: "senbox-org/s2tbx"
      description: "Build submitted via Travis CI"
    notification_email: stb-coverity@thor.si.c-s.fr
    #build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true clean compile"
    branch_pattern: coverity_scan

before_install:
  # Work around discontinued nexus.codehaus.org (see https://github.com/travis-ci/travis-ci/issues/4629)
  # For building, everything is available in nexus.senbox.net, which is stored in pom.xml,
  # so we just completely remove the default repositories settings
  - sed -i -n '/<repositories>/{p; :a; N; /<\/repositories>/!ba; s/.*\n//}; p' ~/.m2/settings.xml
  # Decrypt SSH key for deployment
  - openssl aes-256-cbc -K $encrypted_c14feca833bf_key -iv $encrypted_c14feca833bf_iv -in maintenance/id_rsa_deploynbm.enc -out ~/.ssh/id_rsa_deploynbm -d
  - ssh deploynbm@step.esa.int hello

install:
  - true

script:
  - mvn clean install -B -V

